import 'package:flutter/material.dart';

class AboutScreen extends StatelessWidget {
  const AboutScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF0A1929),
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: Colors.white),
          onPressed: () => Navigator.of(context).pop(),
        ),
        title: const Text(
          'About ClearVote',
          style: TextStyle(
            color: Colors.white,
            fontWeight: FontWeight.bold,
          ),
        ),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // App Logo and Version
            Center(
              child: Column(
                children: [
                  Container(
                    width: 100,
                    height: 100,
                    decoration: BoxDecoration(
                      color: const Color(0xFF4296EA),
                      borderRadius: BorderRadius.circular(24),
                    ),
                    child: const Icon(
                      Icons.how_to_vote,
                      size: 60,
                      color: Colors.white,
                    ),
                  ),
                  const SizedBox(height: 16),
                  const Text(
                    'ClearVote',
                    style: TextStyle(
                      fontSize: 24,
                      fontWeight: FontWeight.bold,
                      color: Colors.white,
                    ),
                  ),
                  const SizedBox(height: 4),
                  const Text(
                    'Version 1.0.0',
                    style: TextStyle(
                      fontSize: 14,
                      color: Colors.white70,
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 32),

            // About Section
            _buildSection(
              title: 'About',
              content: 'ClearVote is a DAO governance tool designed to simplify complex proposals. Our mission is to make decentralized governance more accessible and transparent for all participants.',
            ),
            const SizedBox(height: 24),

            // How to Use Section
            _buildSection(
              title: 'How to Use',
              content: '1. Enter or upload a DAO proposal\n'
                  '2. Adjust the summary length preference\n'
                  '3. Review the AI-generated summary and recommendation\n'
                  '4. Ask follow-up questions for clarification\n'
                  '5. Make an informed voting decision',
            ),
            const SizedBox(height: 24),

            // Features Section
            _buildSection(
              title: 'Features',
              content: '• AI-powered proposal summarization\n'
                  '• Vote recommendations with explanations\n'
                  '• Impact assessment for stakeholders\n'
                  '• Interactive Q&A for deeper understanding\n'
                  '• History of past summaries\n'
                  '• Proposal comparison (coming soon)',
            ),
            const SizedBox(height: 24),

            // Disclaimer Section
            _buildSection(
              title: 'Disclaimer',
              content: 'ClearVote is an assistance tool, not a decision-making system. The summaries and recommendations are generated by AI and should not be the sole basis for your voting decisions. Always review the full proposal before voting.',
              isWarning: true,
            ),
            const SizedBox(height: 24),

            // Contact Section
            _buildSection(
              title: 'Contact',
              content: 'For support or feedback:\nsupport@clearvote.io',
            ),
            const SizedBox(height: 32),

            // Links
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                _buildLinkButton('Privacy Policy'),
                _buildLinkButton('Terms of Service'),
              ],
            ),
            const SizedBox(height: 20),
          ],
        ),
      ),
    );
  }

  Widget _buildSection({
    required String title,
    required String content,
    bool isWarning = false,
  }) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          title,
          style: const TextStyle(
            fontSize: 20,
            fontWeight: FontWeight.bold,
            color: Color(0xFF4296EA),
          ),
        ),
        const SizedBox(height: 8),
        Container(
          width: double.infinity,
          padding: const EdgeInsets.all(16),
          decoration: BoxDecoration(
            color: isWarning ? Colors.amber.withOpacity(0.1) : const Color(0xFF1A2C3D),
            borderRadius: BorderRadius.circular(12),
            border: Border.all(
              color: isWarning ? Colors.amber.withOpacity(0.5) : const Color(0xFF4296EA).withOpacity(0.3),
            ),
          ),
          child: Text(
            content,
            style: TextStyle(
              fontSize: 16,
              color: isWarning ? Colors.amber : Colors.white,
              height: 1.5,
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildLinkButton(String text) {
    return TextButton(
      onPressed: () {
        // In a real app, this would navigate to the respective page
      },
      style: TextButton.styleFrom(
        foregroundColor: const Color(0xFF4296EA),
      ),
      child: Text(text),
    );
  }
}